### ISSUE TITLE
Friends List: Add a Friend

### ISSUE THREAD

**Issue by LukeZvada** [NSS-Day-Cohort-42/nutshell-dog-show-enthusiasts#31]
Given an active user wants to add another user to their friends list, but has no chat messages from that user

When the active user performs a gesture on the 'Add a Friend' affordance

Then the active user will be presented with an input field in which the other user's name can be entered

**Comment by justha** [comment]
"Add a Friend" button now renders "Add Friend Form" with an input field to enter a friend's username
