### ISSUE TITLE
Friends List: Save a Friend / Update Friend List 

### ISSUE THREAD

**Issue by LukeZvada** [NSS-Day-Cohort-42/nutshell-dog-show-enthusiasts#32]
Given an active user has entered in another user's name in order to add that user to their friend list

When the active user performs a gesture on the 'Save' affordance

Then the active user's friends list should be updated with the added user

**Comment by justha** [comment]
Current user can now 'Save' a new friend. 
Save button adds a new friend object to the API. 
friendUserId needs to be validated against existing array of users next...

**Comment by justha** [comment]
friendUserId now saves to API as an integer (that matches the friend's userId)

**Comment by justha** [comment]
'Save Friend' feature now prevents the signed-in user from adding themself or a username that does not exist 
Friend List for current user renders on page load and re-renders when a friend is added
